# This file was generated by GoReleaser. DO NOT EDIT.
cask "ore" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "48e93dc545278bfc56846d1b8bae49e0c75afa40155ec4ce3fce95a5666b66d6"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "02a852bdc5b6bad8c3b3a85d86d4ccc63a14c1c887b6c88524eb321d50e3da4a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "923dbce4a76f298aa3d7408c1190fbd43c5ab9c000bbaa527cb81af0c91bc081"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "66afabc66cc242a762402491d08525e510a86f6356397c95f11550c9b5dc5eaa"
    end
  end

  name "ore"
  desc "Infrastructure-as-Code CLI for game server networks"
  homepage "https://github.com/oreforge/ore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ore"]
    end
  end

  # No zap stanza required

end
