# This file was generated by GoReleaser. DO NOT EDIT.
cask "ore" do
  version "0.0.15"

  on_macos do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "3f4358977b9cd9ca17d363bbcad6c023f487a4fbf60496f4718a97875cbaf538"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "67d252156e098c61090742c0a9592472fa1920819d6dc607b3be9ddcdca01f04"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "ecf8d1179a84df39519d3a5e8810fcb197d69032f4e56d2fafdb3c9cbb8f4a1c"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "73c933322862427dcc7d6bad2b3c7d3aff0ec411eac686ba73a7016c911438a8"
    end
  end

  name "ore"
  desc "Infrastructure-as-Code CLI for game server networks"
  homepage "https://github.com/oreforge/ore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ore"]
    end
  end

  # No zap stanza required

end
