# This file was generated by GoReleaser. DO NOT EDIT.
cask "ore" do
  version "0.0.10"

  on_macos do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "5c8452a412140e0b7f64c941b05d2defa0faa3f68b79356df0dee3d81d29829c"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "73d7ddb5f7a6a7b11524f05d60bdabfdd44ffb8c440af83b27a121dee7d5b370"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "c398a6a56544a4a6a8b9f0bf28e654e6176cf11e609d99a3688a308f31453e0c"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "8b48bb90b2ad1f98a1f5e300000de50e49111835e028328866845e52db35efb8"
    end
  end

  name "ore"
  desc "Infrastructure-as-Code CLI for game server networks"
  homepage "https://github.com/oreforge/ore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ore"]
    end
  end

  # No zap stanza required

end
