# This file was generated by GoReleaser. DO NOT EDIT.
cask "ore@0.0" do
  version "0.0.17"

  on_macos do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "d9105f6f2ce2df1c544a2e1ea4123a7abc01450cf61ad262061a3c0178083c1a"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "33711052acb8d2125db1b821cca1f51326c2a891b69c665683e819b0b37dc889"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "817c594394e9417f93a30cd338a4a2d84f4041d6e929c78fa974841dee9080e7"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "e43e8bd56f4c506c6d99fff031c3692d1ba0155435edcaf6948dfbabb64a689c"
    end
  end

  name "ore@0.0"
  desc "Infrastructure-as-Code CLI for game server networks (v0.0.x)"
  homepage "https://github.com/oreforge/ore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ore"]
    end
  end

  # No zap stanza required

end
