# This file was generated by GoReleaser. DO NOT EDIT.
cask "ore@0.0" do
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "23f18d2f64b5e1ef2785036c468680578e19645444599ba08d9cf0a2aad02083"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "fcc147781787fee86f7c889f32e83ab44b64af140308819d979d8fa9994f2125"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "f4e06f24c0337c45f1744140f2a74e00ea945e3fdfb43588fa261cebc1dde723"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "0d2c435914ad979cd3dd81c07df1f36df005292df925cfd7d71432ee2303c4b6"
    end
  end

  name "ore@0.0"
  desc "Infrastructure-as-Code CLI for game server networks (v0.0.x)"
  homepage "https://github.com/oreforge/ore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ore"]
    end
  end

  # No zap stanza required

end
