# This file was generated by GoReleaser. DO NOT EDIT.
cask "ore@0.0" do
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "7a15d299e956f4928a56f646dfc19740a07b2da20c4a4e85dd43ed8c96379c3a"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "30a265655eb905cab80ea8b2e1971a2ebab8e409cd9e3b8f0cac7089126d24a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "f7614965e561707441360e78759a720cba101c776e182fa749f385eb33638861"
    end
    on_arm do
      url "https://github.com/oreforge/ore/releases/download/v#{version}/ore_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oreforge/ore"
      sha256 "3d4d27c7cfd5d7318513e1f29cf01acd7c6ebd686aba8e978f7de8c061f6ef85"
    end
  end

  name "ore@0.0"
  desc "Infrastructure-as-Code CLI for game server networks (v0.0.x)"
  homepage "https://github.com/oreforge/ore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ore"]
    end
  end

  # No zap stanza required

end
